spring.application.name=chocolatinazo

spring.profiles.active=${SPRING_PROFILES_ACTIVE:test}
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
aws.cognito.region=${AWS_COGNITO_REGION}
aws.cognito.userPoolId=${AWS_COGNITO_USER_POOL_ID}
aws.cognito.clientId=${AWS_COGNITO_CLIENT_ID}
aws.cognito.clientSecret=${AWS_COGNITO_CLIENT_SECRET}
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=${SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_JWK_SET_URI}
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect